spring:
  application:
    name: spzx-manager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.83.123:3306/spzxdb?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 23321212

  #redis
  data:
    redis:
      port: 6379
      host: 192.168.83.123
server:
  port: 8501


#mybatis配置
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*/*.xml
